"use client";

import { useState } from "react";
import type { Spec } from "@/lib/api";

export function SpecCard({
  spec,
  awaiting,
  onDecision,
}: {
  spec: Spec;
  awaiting: boolean;
  onDecision?: (approved: boolean, edited?: Spec) => Promise<void>;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(() => JSON.stringify(spec, null, 2));
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  async function decide(approved: boolean) {
    if (!onDecision) return;
    setError(null);
    let edited: Spec | undefined;
    if (approved && editing) {
      try {
        edited = JSON.parse(draft);
      } catch (e) {
        setError(`Invalid JSON: ${(e as Error).message}`);
        return;
      }
    }
    setBusy(true);
    try {
      await onDecision(approved, edited);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className={`rounded-xl border bg-zinc-900/60 p-4 ${awaiting ? "border-amber-400/60" : "border-zinc-800"}`}>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <h3 className="font-mono text-sm text-zinc-100">{spec.project_name}</h3>
        {spec.auth && <span className="rounded bg-violet-500/15 px-1.5 py-0.5 text-[11px] text-violet-300">JWT auth</span>}
        {(spec.features ?? []).map((f) => (
          <span key={f} className="rounded bg-zinc-800 px-1.5 py-0.5 text-[11px] text-zinc-400">{f}</span>
        ))}
        {awaiting && <span className="ml-auto text-xs text-amber-400">Waiting for your approval</span>}
      </div>
      {spec.description && <p className="mb-3 text-sm text-zinc-400">{spec.description}</p>}

      {editing ? (
        <textarea
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          spellCheck={false}
          className="h-80 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3 font-mono text-xs text-zinc-200 outline-none focus:border-sky-500"
        />
      ) : (
        <div className="grid gap-3 sm:grid-cols-2">
          {spec.auth && (
            <EntityBox name="User" note="generated by auth" fields={[{ name: "email", type: "str", unique: true }, { name: "password_hash", type: "str" }]} />
          )}
          {spec.entities.map((e) => (
            <EntityBox key={e.name} name={e.name} fields={e.fields} />
          ))}
        </div>
      )}

      {awaiting && onDecision && (
        <div className="mt-4 flex flex-wrap items-center gap-2">
          <button
            disabled={busy}
            onClick={() => decide(true)}
            className="rounded-lg bg-emerald-500 px-4 py-1.5 text-sm font-medium text-zinc-950 hover:bg-emerald-400 disabled:opacity-50"
          >
            {editing ? "Approve edited spec" : "Approve & build"}
          </button>
          <button
            disabled={busy}
            onClick={() => setEditing((v) => !v)}
            className="rounded-lg border border-zinc-700 px-3 py-1.5 text-sm text-zinc-300 hover:bg-zinc-800"
          >
            {editing ? "Cancel edit" : "Edit JSON"}
          </button>
          <button
            disabled={busy}
            onClick={() => decide(false)}
            className="rounded-lg px-3 py-1.5 text-sm text-rose-400 hover:bg-rose-500/10"
          >
            Reject
          </button>
          {error && <span className="text-xs text-rose-400">{error}</span>}
        </div>
      )}
    </div>
  );
}

function EntityBox({ name, fields, note }: { name: string; fields: Spec["entities"][number]["fields"]; note?: string }) {
  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-950/60">
      <div className="flex items-center justify-between border-b border-zinc-800 px-3 py-1.5">
        <span className="font-mono text-sm text-sky-300">{name}</span>
        {note && <span className="text-[10px] text-zinc-500">{note}</span>}
      </div>
      <ul className="px-3 py-2 font-mono text-xs">
        <li className="text-zinc-500">id · int · pk</li>
        {fields.map((f) => (
          <li key={f.name} className="text-zinc-300">
            {f.name} <span className="text-zinc-500">· {f.type}</span>
            {f.references && <span className="text-violet-300"> → {f.references}</span>}
            {f.unique && <span className="text-amber-300/80"> · unique</span>}
            {f.required === false && <span className="text-zinc-500"> · optional</span>}
          </li>
        ))}
      </ul>
    </div>
  );
}
